### ISSUE TITLE
[Typo] invalid code?

### ISSUE THREAD

**Issue by xyangwu** [wzzzd/FAQ_system#3]
Hi, 下面这段插入ES数据的代码，`helpers.bulk(es, action)` 是不是要写成`helpers.bulk(es, post_data)`  才对？
```python
for i, line in enumerate(action):
    post_data.append(line)
    if i % interval == 0:
        helpers.bulk(es, action)  # it should be `post_data` instead of  `action` ?
        post_data = []
if post_data:
    helpers.bulk(es, action)
```
source: [insert_data_to_es.py](https://github.com/wzzzd/FAQ_system/blob/4bc8cd9a0388ecc2632c8b54c71b782079c30419/insert_data_to_es.py)

**Comment by wzzzd** [comment]
thx！已经修复相关代码

**Comment by xyangwu** [comment]
cool! 😉
